### ISSUE TITLE
Support java and smali mixed compilation

### ISSUE THREAD

**Issue by only52607** [APKLab/APKLab#168]
The following issue is done with the help of translation software, because my English is not good, I hope there are no grammatical errors, hahaha.

**Is your feature request related to a problem? Please describe.**
It is very common to add new code to an existing project, for example we need to add a new feature to a decompiled project, usually from another third party jar library, but we don't always want to write smali code manually. Usually I create a java project, import the jar library, write some code that invokes the jar, then compile the project's code into a class file and then into a smali file. jar library in the same way, I need to convert the jar package to dex and smali in turn, and finally copy the smali code generated above into the original decompiled project. The above steps are very complicated and I wish there was an easy way to create java files directly in the decompiled project.

**Describe the solution you'd like**
Perhaps we could create a directory called src in the decompiled project, which could have subdirectories called smali, java, lib, etc. The smali directory includes the smali code from the original decompiled project, the java directory includes the new java code we want to add, and the lib directory includes the jar libraries we use . After this, if we want to repackage the apk, the packaging tool will help us compile our java code, smali code, and jar libraries together into a final dex file for repackaging the apk, all this is done automatically.

This is a cool idea, it references the project Efaker/FakerAndroid, I don't know exactly how it is implemented. But it would be very useful to implement something similar.

**Comment by Surendrajat** [comment]
This is a neat idea, and I've been a very happy user of https://github.com/DexPatcher for significant modifications instead of editing smali files. I believe FakerAndroid does something similar as well.
And believe me I thought about integrating DexPatcher when I started working on APKLab. However, there are issues which made me abandon the idea rather quickly:
- VS Code is not good for android (java) development(so much missing stuff) and therefore not suitable for such integration.
- Editing Java directly is really cool when it works but it doesn't always work and is less reliable than editing smali.
- Time. (it will take huge effort to replicate this all in APKLab & VSCode)

I'll leave this open if you want to share some insights contrary to my observations but I honestly I don't think it'll go anywhere (from my end). I'll suggest you to try https://github.com/DexPatcher if it still works.

**Comment by only52607** [comment]
Thank you for your response. This is indeed a massive undertaking, and it is currently quite difficult to implement it within the vscode extension.Thanks for recommending DexPatcher as a great tool! I'll give it a try, even if it hasn't been updated in a while.
