### ISSUE TITLE
Changing .java files doesn't change smali which in turn doesn't reflect on built apk

### ISSUE THREAD

**Issue by rachejazz** [APKLab/APKLab#205]
Hi, I am just following the instructions as given on the README. Ideally making any changes to the decompiled java should reflect on the built apk? I read some blogs where they load the apk on apklab but make changes to smali itself. If that's how it should be done, why do we need apklab at all? isn't old jadx-gui + vim enough?

How do I reflect java changes onto smali?

**Comment by Surendrajat** [comment]
Ideally it should but it doesn't because apklab is just apktool + singer under the hood. The java source is from jadx and is meant to assist you with editing smali files. And yes, you don't need apklab if you can edit smali in vim. The reason I created this tool was to help me with large modifications to APKs and having smali syntax highlighting, symbol lookup, app rebuilding/singing/installing capabilities(for quick iterations) into the editor I use made a lot of sense.

About editing Java files, I've used https://github.com/DexPatcher in the past with some success. Its an incredible tool and it works really well when it does but a little hard to setup initially. You might wanna give it a try.

**Comment by rachejazz** [comment]
Thank you! Will try it out. Please do close this issue if need be. My question is answered
